<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var string $style
 * @var string $locale
 * @var array $defaults
 * @var bool $bibliographic
 * @var bool $append_site
 * @var bool $append_date
 * @var string $tag
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$escape = $plugins->get('escapeHtml');
$api = $this->api();


if (!function_exists('trans'))   {
	function trans($x){
		$cyr = array('а','б','в','г','д','ђ','е','ж','з','и','ј','к','л','љ','м','н','њ','о','п','р','с','т','ћ','у','ф','х','ц','ч','џ','ш','А','Б','В','Г','Д','Ђ','Е','Ж','З','И','Ј','К','Л','Љ','М','Н','Њ','О','П','Р','С','Т','Ћ','У','Ф','Х','Ц','Ч','Џ','Ш');
		$lat = array('a','b','v','g','d','đ','e','ž','z','i','j','k','l','lj','m','n','nj','o','p','r','s','t','ć','u','f','h','c','č','dž','š','A','B','V','G','D','Đ','E','Ž','Z','I','J','K','L','Lj','M','N','Nj','O','P','R','S','T','Ć','U','F','H','C','Č','Dž','Š');
		return  str_replace($cyr, $lat, $x);
	}
}
if (!function_exists('iscyr'))   {
	function iscyr($x){
		$cyr = array('а','б','в','г','д','ђ','е','ж','з','и','ј','к','л','љ','м','н','њ','о','п','р','с','т','ћ','у','ф','х','ц','ч','џ','ш','А','Б','В','Г','Д','Ђ','Е','Ж','З','И','Ј','К','Л','Љ','М','Н','Њ','О','П','Р','С','Т','Ћ','У','Ф','Х','Ц','Ч','Џ','Ш');
		foreach ($cyr as $c){
			if (strpos($x, $c)){ return true; }
		}
		return false;
	}
}

if (is_null($style)):
    $style = 'chicago-fullnote-bibliography';
endif;

try {
    $style = @\Seboettg\CiteProc\StyleSheet::loadStyleSheet($style);
} catch (\Seboettg\CiteProc\Exception\CiteProcException $e) {
    $style = null;
}

if ($style):

    $citeProc = new \Seboettg\CiteProc\CiteProc($style, $locale);
    $csl = $this->rdfToCsl($resource, $defaults);
    // CiteProc fails when the metadata are incomplete.
    try {
        $citation = @$citeProc->render([$csl], 'bibliography');
    } catch (\Exception $e) {
        $vars = $this->vars();
        $vars->offsetSet('style', '');
        echo $this->partial('common/citation', $this->vars());
        return;
    }
    $citation = mb_substr($citation, 52, -13);

else:

    // Format: only pseudo-Chicago is managed when there is no csl.

    $citation = '';
    $creators = $resource->value('dcterms:creator', ['all' => true]) ?: (@$defaults['dcterms:creator'][0]['@value'] ? [$defaults['dcterms:creator'][0]['@value']] : []);
    // Strip formatting and remove empty creator elements.
	$title = $resource->displayTitle();
    $creators = array_values(array_filter(array_map('strip_tags', $creators)));
	
	foreach($creators as $k=>$c){
		if (strpos($c, "item-set/")){
			$id = explode("item-set/", $c)[1];
			$cname = $api->read('item_sets', $id )->getContent()->value('dcterms:title');
			if (!iscyr($title)){$cname = trans($cname);}
			$creators[$k] = $cname;
		}
	}
	
    if ($creators) {
        switch (count($creators)):
        case 1:
            $creator = $creators[0];
            break;
        case 2:
            // Chicago-style item citation: two authors.
            $creator = sprintf($translate('%1$s and %2$s'), $creators[0], $creators[1]);
            break;
        case 3:
            // Chicago-style item citation: three authors.
            $creator = sprintf($translate('%1$s, %2$s, and %3$s'), $creators[0], $creators[1], $creators[2]);
            break;
        default:
            // Chicago-style item citation: more than three authors.
            $creator = sprintf($translate('%s et al.'), $creators[0]);
            break;
        endswitch;
        $citation .= $creator;
    }


    $source = $resource->value('dcterms:source') ?: @$defaults['dcterms:source'][0]['@value'];
	$number = $resource->value('rgf:bibliographicCitationIssue') ?: @$defaults['rgf:bibliographicCitationIssue'][0]['@value'];
	$volume = $resource->value('rgf:bibliographicCitationVolume') ?: @$defaults['rgf:bibliographicCitationVolume'][0]['@value'];
	$date = $resource->value('dcterms:issued') ?: @$defaults['dcterms:issued'][0]['@value'];
	$page = $resource->value('rgf:bibliographicCitationSpage') ?: @$defaults['rgf:bibliographicCitationSpage'][0]['@value'];
	$topage = $resource->value('rgf:bibliographicCitationEpage') ?: @$defaults['rgf:bibliographicCitationEpage'][0]['@value'];
	$doi = $resource->value('bibo:doi') ?: @$defaults['bibo:doi'][0]['@value'];
	
	
	if ($source):
		$citation .= ($citation ? '. ' : '') . '"' . $title . '"';
        $citation .= ' in <i>' . $source . '</i>';
	else:
		$citation .= ($citation ? '. ' : '') . '<i>' . $title . '</i>';
    endif;

	if ($volume):
		$citation .= ' ' . $volume;
	endif;
	
	if ($number):
		$citation .= ' no. ' . $number;
	endif;
	
	

    $publisher = $resource->value('dcterms:publisher') ?: @$defaults['dcterms:publisher'][0]['@value'];
    if ($publisher):
        $citation .= ', ' . $publisher;
    endif;

	if ($date):
		if ($source):
			$citation .= ' (' . $date. ')';
		else:
			$citation .= ', ' . $date;
		endif;
    endif;
	
	if ($page):
		$citation .= ': ' . $page;
		if ($topage):
		$citation .= '-' . $topage;
		endif;
	endif;
	
	
	if ($doi):
        $citation .= '. https://doi.org/' . $doi;
    endif;
    
endif;

$append_date = false;
$append_site = false;

if ($append_site || $append_date):
    $citation = rtrim($citation, '. ');

    if ($append_site):
        if ($site = $this->viewModel()->getRoot()->getVariable('site')):
            $citation .= ', <i>' . $site->title() . '</i>';
        endif;
    endif;

    if ($append_date):
        $accessed = $escape($this->i18n()->dateFormat(new \DateTime(), \Omeka\View\Helper\I18n::DATE_FORMAT_LONG));
        $url = '<span class="citation-url">' . $escape($resource->url(null, true)) . '</span>';
        // Chicago-style item citation: access date and URL.
        $citation .= ', ' . sprintf($translate('accessed %1$s, %2$s'), $accessed, $url);
    endif;

endif;

echo empty($tag) ? $citation : "<$tag class=\"citation\">$citation</$tag>";
