<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \AdvancedSearch\Api\Representation\SearchConfigRepresentation $searchConfig
 * @var \AdvancedSearch\Api\Representation\SearchConfigRepresentation $searchPage Alias of $searchConfig
 * @var \AdvancedSearch\Query $query
 * @var \AdvancedSearch\Response $response
 *
 * Options:
 * @var ?\Omeka\Api\Representation\ItemSetRepresentation $itemSet
 */

if (!isset($response) || empty($searchConfig->subSetting('facet', 'facets'))) return;

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');

$facets = $response->getFacetCounts();
$activeFacets = $response->getActiveFacets();

// Don't display facet groups without facet elements.
$facets = array_filter($facets);

$displayActive = (bool) $searchConfig->subSetting('facet', 'display_active', true);

$isFacetModeButton = $searchConfig->subSetting('facet', 'mode') !== 'link';
$displayFacetButton = $isFacetModeButton && !empty($facets);
$displayButton = $displayFacetButton ? $searchConfig->subSetting('facet', 'display_button', 'above') : 'none';

$facetActive = $plugins->get('facetActive');
$facetLabel = $plugins->get('facetLabel');
// Facet checkbox can be used in any case anyway, the js checks it.
$facetElements = $isFacetModeButton ? $plugins->get('facetCheckboxes') : $plugins->get('facetLinks');
$facetSelect = $plugins->get('facetSelect');
$facetSelectRange = $plugins->get('facetSelectRange');

@$year_range_arr = array_map('intval', explode(',', $this->themeSetting('intervals')));
$year_field = $this->themeSetting('yearfield');
$thisyear = date("Y");

// Don't display facets for item sets when browsing an item set.
if (!empty($itemSet)) {
    unset($facets['item_set_id']);
    unset($activeFacets['item_set_id']);
}

$options = $searchConfig->setting('facet', []);
?>

<aside class="search-facets">

    <?php if ($facetsLabel = $searchConfig->subSetting('facet', 'label', $translate('Facets'))): ?>
    <h3><?= $escape($facetsLabel) ?></h3>
    <?php endif; ?>

    <?php if ($displayActive && count($activeFacets)): ?>
    <h4><?= $translate('Active facets') ?></h4>
    <ul class="search-facets-active">
        <?php foreach ($activeFacets as $name => $facetValues) foreach ($facetValues as $facetKey => $facetValue): ?>
        <li><?= $facetActive($name, ['value' => $facetValue, 'count' => null, 'key' => $facetKey], $options) ?></li>
        <?php endforeach; ?>
    </ul>
    <?php endif; ?>

    <form id="form-facets">

        <?php if ($displayFacetButton): ?>
        <?= $this->hiddenInputsFromFilteredQuery(null, ['facet', 'page', 'limit', 'offset', 'per_page']) ?>
        <?php endif; ?>

        <?php if ($displayFacetButton && ($displayButton === 'above' || $displayButton === 'both')): ?>
        <div class="apply-facets apply-facets-top">
            <button id="apply-facets" type="submit"><?= $translate('Apply facets') ?></button>
        </div>
        <?php endif; ?>

        <?php if (empty($facets) && empty($activeFacets)): ?>
        <p><?= $translate('No facets.') ?></p>
        <?php else: ?>
        <ul class="search-facets-list">
            <?php foreach ($facets as $name => $facetValues): ?>
            <?php $facetType = empty($options['facets'][$name]['type']) ? 'Checkbox' : $options['facets'][$name]['type']; ?>
            <li class="search-facet">
                <h4><?= $translate($facetLabel($name)) ?></h4>
                <?php if ($facetType === 'Select'): ?>
                <?= $facetSelect($name, $facetValues, $options) ?>
                <?php elseif ($facetType === 'SelectRange'): ?>
                <?= $facetSelectRange($name, $facetValues, $options) ?>
                <?php else: ?>
                <?= $facetElements($name, $facetValues, $options) ?>
                <?php endif; ?>
            </li>
            <?php endforeach; ?>
			
			
			
			<?php
			@$year_range_arr = array_map('intval', explode(',', $this->themeSetting('intervals')));
			$year_field = $this->themeSetting('yearfield');
			
			if (!empty($year_range_arr)){ if ($year_range_arr!=[0]){
				$thisyear = date("Y");
			?>
			
			<li class="search-facet">
				<h4><?php echo $this->translate('Period'); ?></h4>                    
				<ul class="search-facet-items">
				<?php 
					foreach($year_range_arr as $n){ 
						if ($n > 0){
							echo '<li class="inactive" onclick="lastx('.$n.', '.$thisyear.', \''.$year_field.'\')"><a>';
							if ($n==1){
								echo $thisyear;
							}
							else{
								echo $this->translate('from')." ".($thisyear+1-$n)." ".$this->translate('to')." ".$thisyear;
							}
							echo " (".$n." ".$this->translate('year').")";
							echo "</a></li>";
						}
					}
				?>
				</ul>
			</li>

			<?php }} ?>

        </ul>
        <?php endif; ?>

        <?php if ($displayFacetButton && ($displayButton === 'below' || $displayButton === 'both')): ?>
        <div class="apply-facets apply-facets-bottom">
            <button id="apply-facets" type="submit"><?= $translate('Apply facets') ?></button>
        </div>
        <?php endif; ?>

    </form>

</aside>
